### ISSUE TITLE
Lock Threads

### ISSUE THREAD

**Issue by ezfe** [Mojira/Arisa#17]
On Reddit there is a thread locking feature using Autobot, where new comments are deleted. This would be extremely useful on threads that have been resolved but are still receiving lots of comments / hate (we've had to close tickets in the past). Obviously would need some tweaking and an easy way to trigger.

**Comment by Synchunk** [comment]
Wouldn't re-enabling the "Close Issue" transition be the best solution to that?

**Comment by ezfe** [comment]
could be, but I thought this might be a more elegant solution that allows us to comment on them. Idk just an idea.

**Comment by Tora-B** [comment]
I believe moderators are still able to comment on closed issues.

**Comment by ezfe** [comment]
Fair point
