### ISSUE TITLE
Link to report issue should be changed

### ISSUE THREAD

**Issue by calebsander** [Mojira/Arisa#19]
https://github.com/Mojira/Arisa/issues -> https://github.com/Mojira/Arisa/issues/new

**Comment by calebsander** [comment]
Also not sure what the purpose of COMMENT_FOOTER_ARGS is.

**Comment by Synchunk** [comment]
@calebsander In `responses/footer` (just like in `responses/duplicate/duplicate`), you can use `%s` for certain variables. The bot will then later replace that with a new value. For example, `COMMENT_FOOTER_ARGS` is used as follows:
```ruby
footer % COMMENT_FOOTER_ARGS
```
That replaces every `%s` with the corresponding item in the `COMMENT_FOOTER_ARGS` array.

This way you don't need to hardcode the URL in `responses/footer` and you can keep everything important in one place – your configuration directory.

**Comment by Synchunk** [comment]
Done in 1b5c0762bcf5e4619ad87b6804e14691c6b2d1fe.

**Comment by Tora-B** [comment]
Why would you want to link directly to creating a new issue? That's just asking for duplicate reports, though it's admittedly unlikely that very many people will report any issues with the bot.

**Comment by Mustek** [comment]
+1 for Tora-B

---
Kevin Pletinckx

**Comment by Synchunk** [comment]
Good point, should I change it back?
